from slack_bolt import Ack, Respond
from logging import Logger
import ollama
import random

# Replace with your actual channel ID
IT_SUPPORT_CHANNEL_ID = "C07TFNLM4LW"
IT_SUPPORT_SPECIALISTS = {
    "D07TN6R3KLJ": "Max Tran",
    "D07TQMKFAEQ": "Duc Pham",
    "D07TN44FWSF": "Joe McMahon",
    "D07TQMKE52Q": "Anthea Z"
}
LLM_CONTEXT_TEMPLATE = "" # TODO feed llm context from RAG here
PROMPT_TEMPLATE = (
    "You are an IT support. Given the general IT knowledge and this context {context}\n"
    "\n"
    "I'll ask you a question. If it's not related to IT, please reply with 'I can only answer IT questions'."
    "If it's related to IT, please give me a concise paragraph answer."
    "If you can't answer the IT question, just reply with 'IDK the answer to this question'\n"
    "{prompt}"
)

def get_it_specialist_id():
    it_specialist_id = random.choice(IT_SUPPORT_SPECIALISTS.keys())
    print(f'The chosen it specialist: {it_specialist_id}')
    return it_specialist_id

def generate_llm_response(prompt):
    llm_context = LLM_CONTEXT_TEMPLATE

    llm_prompt = PROMPT_TEMPLATE.format(
        context=llm_context,
        prompt=prompt
    )
    response = ollama.chat(model='llama3.2', messages=[
        {
            'role': 'user',
            'content': llm_prompt,
        },
    ])
    return response['message']['content']

# Out of scope
# def converse_with_ollama(initial_question, model='llama3.2'):
#     messages = [{'role': 'user', 'content': initial_question}]
#     while True:
#         # Send the messages to Ollama
#         response = ollama.chat(model=model, messages=messages)
#         assistant_reply = response['content']
#         print(f"Assistant: {assistant_reply}\n")
#
#         # Append the assistant's reply to the conversation
#         messages.append({'role': 'assistant', 'content': assistant_reply})
#
#         # Get the next user input
#         user_input = input("You: ")
#         if user_input.lower() in ('exit', 'quit'):
#             break
#         messages.append({'role': 'user', 'content': user_input})

def it_support_callback(command, ack: Ack, respond: Respond, logger: Logger):
    try:
        ack()
        channel_id = command['channel_id']
        user_id = command['user_id']
        user_input = command.get('text', '')

        if channel_id != IT_SUPPORT_CHANNEL_ID:
            respond(
                response_type="ephemeral",
                blocks=[
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": f"<@{user_id}> requested IT support: {user_input}"
                        }
                    },
                    {
                        "type": "section",
                        "text": {
                            "type": "mrkdwn",
                            "text": "Currently, we can't help you. You can call *123-456-7890* for help."
                        }
                    }
                ]
            )
            logger.info(f"Unauthorized use of /it-support by <@{user_id}> in channel <#{channel_id}>.")
            return

        ollama_output = generate_llm_response(user_input)
        it_specialist_id = get_it_specialist_id()
        if 'IDK' in ollama_output:
            ollama_output += f"\n<@{it_specialist_id}>, can you answer this?"

        respond(
            response_type="in_channel",
            blocks=[
                # User's request
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*<@{user_id}> requested IT support:*\n>{user_input}"
                    }
                },
                # Divider
                {
                    "type": "divider"
                },
                # Bot's response
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f":robot_face: *Slackbot Response:*\n{ollama_output}\n"
                    }
                },
                # Context block indicating it's generated by the Slackbot
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": "_Generated by IT Support slackbot_"
                        }
                    ]
                }
            ]
        )
    except Exception as e:
        logger.error(f"Error in it_support_callback: {e}")